Use Fisherman instead of Wahoo

diff --git a/bin/cargo-cov b/bin/cargo-cov
--- a/bin/cargo-cov
+++ b/bin/cargo-cov
@@ -1,17 +1,26 @@
 #!/bin/bash
 PKGID="$(cargo pkgid)"
 [ -z "$PKGID" ] && exit 1
+
 ORIGIN="${PKGID%#*}"
 ORIGIN="${ORIGIN:7}"
 PKGNAMEVER="${PKGID##*/}"
 PKGNAME="${PKGNAMEVER%#*}"
+
 shift
-cargo test --no-run || exit $?
-EXE=($ORIGIN/target/debug/$PKGNAME-*)
-if [ ${#EXE[@]} -ne 1 ]; then
-    echo 'Non-unique test file, retrying...' >2
-    rm -f ${EXE[@]}
-    cargo test --no-run || exit $?
-fi
+
 rm -rf $ORIGIN/target/cov
-kcov --verify --exclude-pattern=cargo,/usr,/lib $ORIGIN/target/cov $ORIGIN/target/debug/$PKGNAME-* "$@"
+
+# find $ORIGIN/target/debug -maxdepth 1 -executable -and -type f -delete
+cargo test --no-run || exit $?
+
+# EXE=($ORIGIN/target/debug/$PKGNAME-*)
+# if [ ${#EXE[@]} -ne 1 ]; then
+#     echo 'Non-unique test file, retrying...' >2
+#     rm -f ${EXE[@]}
+#     cargo test --no-run || exit $?
+# fi
+
+
+find $ORIGIN/target/debug -maxdepth 1 -executable -and -type f -print0 \
+  | xargs -0I@ kcov --include-path=src $ORIGIN/target/cov @ "$@"
